### ISSUE TITLE
Safari 10.1 Support

### ISSUE THREAD

**Issue by chasegiunta** [bfred-it/scroll-restoration-polyfill#1]
Hey there, appreciate the polyfill!

Not supported in the latest Safari, though. Verified with Demo.
Safari Version 10.1 (12603.1.30.0.34) on MacOS Sierra 10.12.4

**Comment by fregante** [comment]
It works here 

![screencast](https://cloud.githubusercontent.com/assets/1402241/26437742/84ce101c-4151-11e7-9ac3-72fd6a623d65.gif)

**Comment by fregante** [comment]
And on macOS 10.12 (via browserstack) (don't mind the flashing at the end, it's a GIF artifact)

![screencast](https://cloud.githubusercontent.com/assets/1402241/26437911/74a6ec76-4152-11e7-9d75-5ad3f0d39c5f.gif)
